name: automated-calibration-for-musical-instruments CI

on: [push, pull_request]

jobs:
  build:

    runs-on: self-feelpp

    steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v6
              with:
                version: "latest"
            
            - name: setup Python Venv and install dependencies
              run: |
                python3 -m venv myenv
                source myenv/bin/activate
                pip install -r requirements.txt
                pip install -e .

            - name: Discontinuous Galerkin tests
              run: |
                source myenv/bin/activate
                cd tests/
                pytest test.py -v

            - name: Generate Report pdf
              run: |
                cd doc/Rapport
                pdflatex rapport_stage.tex
                biber rapport_stage
                pdflatex rapport_stage.tex
                pdflatex rapport_stage.tex

            - name: Generate Presentation pdf
              run: |
                cd doc/Oral
                pdflatex oral_stage_M2_Rodolphe_Vivant.tex
                biber oral_stage_M2_Rodolphe_Vivant
                pdflatex oral_stage_M2_Rodolphe_Vivant.tex
                pdflatex oral_stage_M2_Rodolphe_Vivant.tex